server:

  port: 9527



spring:

  application:

    name: springcloud-zuul-gateway


eureka:

  client: #客户端注册进eureka服务列表内

    service-url:

      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:

    instance-id: gateway-9527.com   #自定义服务名称信息

    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: springcloud
  company.name: com.zzcedu
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**
  prefix: /edu
  ignored-services: "*"